### ISSUE TITLE
Any base system other than 'simpleSystemBase' is not working on macOs High Sierra

### ISSUE THREAD

**Issue by wilberbeast** [kquick/Thespian#8]
Hi,
I've attempted even the simplest examples, such as the following:

`_from thespian.actors import *

class Hello(Actor):
	def receiveMessage(self, message, sender):
		# self.send(sender, "Hello, world!")
		self.send(sender, 'Yes, I am there.')

def say_hello():
	asys = ActorSystem()
	asys = ActorSystem('multiprocTCPBase')
	# hello = asys.createActor(Hello)
	print(ActorSystem().ask(hello, 'are you there?', 1.5))

if __name__ == "__main__":
	say_hello()	
_`

If I switch between ActorSystem() and ActorSystem('multiprocTCPBase') I receive the following errors:
_Traceback (most recent call last):
  File "test.py", line 15, in <module>
    say_hello()	
  File "test.py", line 11, in say_hello
    hello = asys.createActor(Hello)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thespian/actors.py", line 697, in createActor
    sourceHash)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/thespian/system/systemBase.py", line 197, in newPrimaryActor
    response.failure_message)
thespian.actors.InvalidActorSpecification: Invalid Actor Specification: <class '__main__.Hello'> (module '__main__' has no attribute 'Hello')_

Any help appreciated.

Steve

**Comment by kquick** [comment]
Hi Steve,

I uncommented the `hello = ...` line, and commented out the first `ActorSystem()` line above and was able to run your example using Thespian 3.8.0 on my Mac running El Capitan without difficulties.  It may be possible that there is something in High Sierra, but more likely you are encountering this behavior: http://thespianpy.com/doc/in_depth.html#outline-container-hH-1b595f63-447b-40d1-ad52-582e4ac7a536

Basically, you probably ran this previously when there was no ```class Hello(Actor):``` defined, and the TCP admin actor was cloned with that code state.  Updating your local code does not update the admin actor's memory, so it keeps responding from that previous version with the error above.

You can confirm this via: `$ netstat -nv | grep 1900` and if there are multiple lines shown, then there is definitely a Thespian admin still running.

You have three options:
1. Add an ActorSystem().shutdown() into your code above.
2. Manually shutdown the system via either a `kill` command on the processes involved, or using the thespian shell:
```
    $ python -m thespian.shell
    thespian> start multiprocTCPBase
    thespian> stop
    thespian> exit
```
3. Use loadable sources as describe here: http://thespianpy.com/doc/in_depth.html#outline-container-hH-7b9dbba0-c492-48db-ad43-a94d3e1bef8d.  This is a bit more advanced, so when you are starting out, I'd recommend #1, but using loadable sources has a lot of other advantages as well.  The thespian director can help with creating an managing loadable sources (`$ python -m thespian.director` and `$ python -m thespian.director help gensrc`).

Let me know if you still have problems,
  -Kevin

**Comment by wilberbeast** [comment]
Hi Kevin,

Thanks for the quick response. I’ll try out your possible solutions later tonight and I’ll let you know how I get on.

Cheers

Steve

**Comment by wilberbeast** [comment]
Hi,

Thanks for the response. I’m making progress. I keep having to strip the code down to the bare minimum and then tentatively add bits step by step.

By the way, what’s the best way of preventing the __main__ code from just dropping out the bottom and exiting the code. I intend to have long running polling going on, but the code just exits. I’m new to python, so I’m not sure of the best ways to do things at the mo. Currently I’m just making the ActorSystem ask an actor that doesn’t ever return, but that doesn’t seem ideal.

Once again, thanks for your help.

Cheers

Steve

**Comment by kquick** [comment]
Hi Steve,

It depends on what you want the main code to do.  

If you are using multiprocTCPBase as the Actor base, then the actors will continue to run even when your main application exits.  Running another application that calls `ActorSystem("multiprocTCPBase")` will re-connect to that same system.  If you need to be able to address a previously created actor in the new application, use the globalName when originally creating that actor and the new application just issues a create with that same globalName and it will return the address of the already running actor instead of creating a new one.

Alternatively, if you just want your main application to continue to run, I find `signal.pause()` to be very useful (you need to `import signal` for this) because it will block until you hit Ctrl-C (or it receives some other signal).

And of course, you've found a perfectly workable method.  It is a bit unconventional, but I don't see anything particularly wrong with that approach.

If my suggestion above helped, you may want to close this issue and ask further help-oriented questions on the mailing list (see http://thespianpy.com/doc/#outline-container-orgheadline13).

Regards,
  Kevin

**Comment by kquick** [comment]
Hi @wilberbeast ,

Just checking in to see how you are doing.  Did you want any more assistance, and/or do you want to close this issue?

Regards,
  Kevin

**Comment by kquick** [comment]
Closing due to inactivity.  Please feel free to re-open this if you need more assistance.
